name: Alpha Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Runtipi version (3.0.0, 3.0.0-beta.5...)"
        required: true
      distinct_id:
        type: string
        description: "Distinct ID"
        required: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: echo distinct ID ${{ github.event.inputs.distinct_id }}
        run: echo ${{ github.event.inputs.distinct_id }}

  create-tag:
    runs-on: ubuntu-latest
    outputs:
      tagname: ${{ steps.create_tag.outputs.tagname }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create tag
        id: create_tag
        run: |
          echo "tagname=v${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT

      - uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ steps.create_tag.outputs.tagname }}

  build-image:
    runs-on: ubuntu-latest
    needs: create-tag
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install apt requirements
        run: sudo apt install coreutils quilt parted qemu-user-static debootstrap zerofree zip dosfstools libarchive-tools libcap2-bin grep rsync xz-utils file git curl bc qemu-utils kpartx gpg pigz sed -y

      - name: Set runtipi version
        run: |
          sed -i "s|RUNTIPI_VERSION=runtipi_version # Specify a version|RUNTIPI_VERSION=${{ github.event.inputs.version }}|" config

      - name: Build Image
        run: ./build-docker.sh

      - name: Upload the image
        uses: actions/upload-artifact@v3
        with:
          name: image
          path: deploy/

  publish-release:
    runs-on: ubuntu-latest
    needs: [create-tag, build-image]

    steps:
      - name: Download image
        uses: actions/download-artifact@v3
        with:
          name: image
          path: image/

      - name: Get image name
        id: get_img
        run: |
          image=$(find image/ -iname *.zip)
          echo "img_name=${image}" >> $GITHUB_OUTPUT

      - name: Rename image
        run: |
          mv ${{ steps.get_img.outputs.img_name }} ./runtipi-os-v${{ needs.create-tag.outputs.tagname }}.zip

      - name: Create alpha release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.create-tag.outputs.tagname }}
          name: v${{ needs.create-tag.outputs.tagname }}
          prerelease: true
          files: |
            runtipi-os-v${{ needs.create-tag.outputs.tagname }}.zip
